### ISSUE TITLE
Error compiling on Ubuntu 14.04

### ISSUE THREAD

**Issue by cam1878** [erikkaashoek/Comskip#37]
I've followed the instructions in the readme for compiling on 14.04.

I ran into the same issue posted here:
[https://github.com/erikkaashoek/Comskip/issues/36](36)

However as mentioned in the comments there, compiling the most recent ffmpeg from scratch solved it.

Now that I was able to properly configure, I've run into this error while compiling:
```
gcc -DPACKAGE_NAME=\"Comskip\" -DPACKAGE_TARNAME=\"comskip\" -DPACKAGE_VERSION=\"0.81.089\" -DPACKAGE_STRING=\"Comskip\ 0.81.089\" -DPACKAGE_BUGREPORT=\"https://github.com/erikkaashoek/Comskip/issues\" -DPACKAGE_URL=\"\" -DPACKAGE=\"comskip\" -DVERSION=\"0.81.089\" -DHAVE_LIBM=1 -DHAVE_LIBPTHREAD=1 -I.  -Wall  -I/usr/local/include   -DPROCESS_CC -DDONATOR  -g -O2  -MT comskip-mpeg2dec.o -MD -MP -MF .deps/comskip-mpeg2dec.Tpo -c -o comskip-mpeg2dec.o `test -f 'mpeg2dec.c' || echo './'`mpeg2dec.c
In file included from mpeg2dec.c:170:0:
comskip.h:5:0: warning: "PACKAGE_STRING" redefined [enabled by default]
 #define PACKAGE_STRING " Comskip 0.81.090"
 ^
<command-line>:0:0: note: this is the location of the previous definition
mpeg2dec.c: In function 'DecodeOnePicture':
mpeg2dec.c:1064:17: warning: 'av_free_packet' is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4040) [-Wdeprecated-declarations]
                 av_free_packet(packet);
                 ^
mpeg2dec.c:1096:21: warning: 'av_free_packet' is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4040) [-Wdeprecated-declarations]
                     av_free_packet(packet);
                     ^
mpeg2dec.c:1122:9: warning: 'av_free_packet' is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4040) [-Wdeprecated-declarations]
         av_free_packet(packet);
         ^
mpeg2dec.c: In function 'stream_component_open':
mpeg2dec.c:1595:35: error: 'CODEC_ID_MPEG1VIDEO' undeclared (first use in this function)
         if (codecCtx->codec_id != CODEC_ID_MPEG1VIDEO)
                                   ^
mpeg2dec.c:1595:35: note: each undeclared identifier is reported only once for each function it appears in
mpeg2dec.c:1603:35: error: 'CODEC_ID_H264' undeclared (first use in this function)
         if (codecCtx->codec_id == CODEC_ID_H264) {
                                   ^
mpeg2dec.c: In function 'file_open':
mpeg2dec.c:1793:23: error: 'AVFormatContext' has no member named 'max_analyze_duration2'
         is->pFormatCtx->max_analyze_duration2 *= 4;
                       ^
mpeg2dec.c: In function 'main':
mpeg2dec.c:2163:21: warning: 'av_free_packet' is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4040) [-Wdeprecated-declarations]
                     av_free_packet(packet);
                     ^
mpeg2dec.c:2288:13: warning: 'av_free_packet' is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4040) [-Wdeprecated-declarations]
             av_free_packet(packet);
             ^
make: *** [comskip-mpeg2dec.o] Error 1
```

Any suggestions would help, thanks.

**Comment by tmm1** [comment]
Looks like you didn't build your ffmpeg with mpeg and h264 support.

**Comment by cam1878** [comment]
I used this script to compile everything:
[https://gist.github.com/xdamman/e4f713c8cd1a389a5917](https://gist.github.com/xdamman/e4f713c8cd1a389a5917)

It seems to be just an automated script of this:
[https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu](https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu)

But h264 support is definitely in there.

**Comment by gdevenyi** [comment]
Your problem is trying to build with ffmpeg-3.0, seems whatever changes were made there aren't supported by comskip yet.

I had the same error, so I went back and downloaded and built 2.4.13 by the same method and everything works.

**Comment by tmm1** [comment]
cc @fflewddur
